### ISSUE TITLE
Correção ortográfica e melhoria no primeiro capítulo

### ISSUE THREAD

**Issue by ffsouzace** [ufpb-computacao/introducao-a-programacao-livro#27]
No período: "Entradas: Um algoritmo deve possuir zero ou mais entradas. Estas são insumos ou quantidades que são processados pelos algoritmos durante a execução de seus passos.",
eu sugiro colocar: ... Estas são insumos (mais precisamente, os dados) que são processados...

Já no período: "Saídas: Um algoritmo deve possuir uma ou mais saídas. Elas representam o resultado do trabalhado realizado pelos algoritmos.", deve ser trocada a palavra "trabalhado" por "trabalho".

Cap. 1, pag. 4, versão=?

**Comment by edusantana** [comment]
Oi @ffsouzace irei corrigir o erro e verificar a melhoria indicada, obrigado!

**Comment by edusantana** [comment]
Oi @ffsouzace , obrigado por sua contribuição.

[A alteração](https://github.com/ufpb-computacao/introducao-a-programacao-livro/commit/da193452cae70325d9faf305af2ab4e58a2ea224) foi realizada no repositório e sairá na próxima versão do livro.

Grato por sua contribuição!
